This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./monografia.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file monografia.acn....done (213 entries accepted, 0 rejected).
Sorting entries.....done (1721 comparisons).
Generating output file monografia.acr....done (58 lines written, 0 warnings).
Output written in monografia.acr.
Transcript written in monografia.alg.
